apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-native-onprem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gforns/argocd-operator-sample.git
    targetRevision: HEAD
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true